Refactoring : Essential because there is a conflict between Twitter and Elasticsearch dependencies : NoClassDefFoundError org/apache/http/client/config/RequestConfig => Separation of the 2 dependencies in 2 distinct pom xml files